Repository SWM14-Architect/moview-frontend, pull requests merged in 2023-09, with the labels that each got.

#20 문서 작업 및 버그 수정
  .env.production
  README.md
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/store/interviewChatAtom.js
  src/store/interviewRoomAtom.js
Labels: fix, docs, comment

#21 Feat: 클라이언트측에서 면접 상태를 관리하도록 변경
  README.md
  package-lock.json
  package.json
  src/App.js
  src/api/interview.js
  src/api/interviewee.js
  src/components/header.jsx
  src/components/loading.jsx
  src/constants/interviewRoomConst.js
  src/index.js
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/store/interviewChatAtom.js
  src/store/interviewRoomAtom.js
  src/store/loadingAtom.js
  src/styles/index.css
  src/styles/loading.css
  src/utils/interviewSummaryGenerator.js
Labels: docs, feat, chore, design, refactor

#22 Release v1
  README.md
  package-lock.json
  package.json
  src/App.js
  src/api/interview.js
  src/api/interviewee.js
  src/components/header.jsx
  src/components/loading.jsx
  src/constants/interviewRoomConst.js
  src/index.js
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/store/interviewChatAtom.js
  src/store/interviewRoomAtom.js
  src/store/loadingAtom.js
  src/styles/index.css
  src/styles/loading.css
  src/utils/interviewSummaryGenerator.js
Labels: release

#23 fix: API Endpoint 변경
  .env.production
Labels: fix

#24 Release v1.1
  .env.production
Labels: release

#25 HotFix: 인터뷰 중간종료시 Alert 메시지 삭제
  src/components/header.jsx
Labels: hotfix

#26 Release v1.2
  src/components/header.jsx
Labels: release

#27 Feat google analytics
  .env
  package-lock.json
  package.json
  src/App.js
  src/RouteChangeTracker.js
  src/index.js
Labels: feat

#28 구글 분석 추가
  .env
  package-lock.json
  package.json
  src/App.js
  src/RouteChangeTracker.js
  src/index.js
Labels: feat

#30 Feat: Kakao OAuth 추가
  package-lock.json
  package.json
  src/App.js
  src/JWT.js
  src/RouteChangeTracker.js
  src/api/api_instance.js
  src/api/interview.js
  src/api/jwt.js
  src/assets/free-icon-close-151882.png
  src/assets/free-icon-hamburger-7710488.png
  src/assets/kakaolink_btn_small.png
  src/components/footer.jsx
  src/components/header.jsx
  src/components/mobile-only/hamburgerButton.jsx
  src/constants/apiConst.js
  src/fonts/KakaoRegular.woff
  src/index.js
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/login_callback.jsx
  src/pages/main.jsx
  src/store/userAtom.js
  src/styles/animation.css
  src/styles/footer.module.css
  src/styles/hamburgerButton.module.css
  src/styles/header.module.css
  src/styles/layout.css
  src/styles/main.module.css
  src/styles/oauth.module.css
  src/utils/useCookie.js
Labels: chore, design, refactor
