Repository SWM14-Architect/moview-frontend, pull requests merged in 2023-10, with the labels that each got.

#31 라이트 모드 추가 및 UI 변경
  package-lock.json
  package.json
  src/api/interview.js
  src/assets/interviewer.png
  src/assets/logo192.png
  src/assets/pexels-edmond-dantes.jpg
  src/assets/pexels-tima-miroshnichenko.jpg
  src/components/footer.jsx
  src/components/header.jsx
  src/components/mobile-only/hamburgerButton.jsx
  src/index.js
  src/pages/interviewRoom.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/pages/main.jsx
  src/pages/modeSelect.jsx
  src/styles/button.hover.css
  src/styles/index.css
  src/styles/interviewLightInput.module.css
  src/styles/modelSelect.module.css
  tailwind.config.js
Labels: feat, design

#34 Feat/tts and stt
  src/App.js
  src/api/interview.js
  src/assets/record-start.jpg
  src/assets/record-stop.jpg
  src/components/loading.jsx
  src/pages/error_page.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/store/interviewChatAtom.js
  src/store/interviewRoomAtom.js
  src/store/loadingAtom.js
  src/styles/interviewChat.module.css
  src/utils/audioRecorder.js
  src/utils/interviewSummaryGenerator.js
  src/utils/toastContainer.jsx
  src/utils/useInterval.js
  src/utils/useTTSPlayer.js
  src/utils/useTitle.js
Labels: feat

#36 feat: 입력 글자수 제한 기능 추가
  src/api/interview.js
  src/constants/interviewChatConst.js
  src/constants/interviewInputConst.js
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/styles/interviewInput.module.css
Labels: feat

#37 fix: 백엔드 서버와 일치하지 않는 제약조건 수정
  src/constants/interviewInputConst.js
Labels: fix

#38 fix: 글자수 제한에 의해 글자가 제거 되었을 때 textarea height resize가 정상적으로 작동하지 않던 문제 해결
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
Labels: fix

#39 fix: 녹음 오류 수정
  src/utils/audioRecorder.js
Labels: fix

#41 Feat temp save
  src/assets/free-icon-man-3884851-p-500.png
  src/assets/free-icon-man-4086624-p-500.png
  src/assets/howto/how-to-add-req.png
  src/assets/howto/how-to-chat-mic-edit.png
  src/assets/howto/how-to-chat-mic-off.png
  src/assets/howto/how-to-chat-mic-on.png
  src/assets/howto/how-to-chat-type.png
  src/assets/howto/how-to-input.jpeg
  src/assets/howto/how-to-light.png
  src/assets/howto/how-to-select-mode.png
  src/assets/pexels-fauxels-3182765_gnR1cf24-p-1080.webp
  src/assets/recruitment-6838250_1920.png
  src/components/SaveProgess.jsx
  src/components/header.jsx
  src/index.js
  src/pages/howto.jsx
  src/pages/interviewRoom/interviewChat.jsx
Labels: feat

#43 Feat/dev cicd
  .env.production-dev
  .env.production-main
  .github/workflows/cicd.yml
  .github/workflows/dev_push.yml
  .github/workflows/main_push.yml
Labels: feat

#44 Feat: Feedback Modal 추가
  package-lock.json
  package.json
  src/App.js
  src/api/slack.js
  src/components/feedbackModal.jsx
  src/components/header.jsx
  src/constants/interviewFeedbackConst.js
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/pages/main.jsx
  src/pages/modeSelect.jsx
  src/store/modalAtom.js
  src/styles/button.hover.css
  src/styles/feedbackModal.module.css
  src/styles/main.module.css
  tailwind.config.js
Labels: feat, chore, design

#48 hotfix : 모바일에서 사용방법 핸들러 드러나던 것 수정
  src/components/header.jsx
Labels: hotfix

#51 Fix: Minor Bug
  package.json
  src/api/api_instance.js
  src/assets/pexels-tima-miroshnichenko.jpg
  src/components/SaveProgess.jsx
  src/components/feedbackModal.jsx
  src/components/header.jsx
  src/pages/error_page.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/pages/main.jsx
  src/utils/useTTSPlayer.js
Labels: fix, feat

#57 Refactor: API Refactoring
  src/App.js
  src/RouteChangeTracker.js
  src/api/api_instance.js
  src/api/interview.js
  src/api/jwt.js
  src/api/slack.js
  src/components/footer.jsx
  src/pages/main.jsx
  src/styles/main.module.css
Labels: design, refactor

#56 Fix problems
  src/components/SaveProgess.jsx
  src/constants/interviewInputConst.js
  src/pages/howto.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
Labels: design

#58 Release v3.1
  package.json
  src/App.js
  src/RouteChangeTracker.js
  src/api/api_instance.js
  src/api/interview.js
  src/api/jwt.js
  src/api/slack.js
  src/assets/pexels-tima-miroshnichenko.jpg
  src/components/SaveProgess.jsx
  src/components/feedbackModal.jsx
  src/components/footer.jsx
  src/components/header.jsx
  src/constants/interviewInputConst.js
  src/pages/error_page.jsx
  src/pages/howto.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/pages/main.jsx
  src/styles/main.module.css
  src/utils/useTTSPlayer.js
Labels: release

#59 Feat: Kakao Pixel SDK
  .env
  .env.production-dev
  .env.production-main
  public/index.html
  src/components/loading.jsx
  src/index.js
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/pages/login_callback.jsx
  src/styles/loading.css
Labels: feat

#60 feat : 503 에러일 경우 1분 기다려달라고 토스트로 표시하게 함.
  src/api/api_instance.js
  src/components/header.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/main.jsx
Labels: feat

#62 Design: Main 페이지 디자인 수정
  src/App.js
  src/assets/free-icon-close-151882.png
  src/assets/free-icon-hamburger-7710488.png
  src/assets/free-icon-interview-7659465.png
  src/assets/howto/how-to-add-req.png
  src/assets/howto/how-to-chat-mic-edit.png
  src/assets/howto/how-to-chat-mic-off.png
  src/assets/howto/how-to-chat-mic-on.png
  src/assets/howto/how-to-chat-type.png
  src/assets/howto/how-to-input.jpeg
  src/assets/howto/how-to-light.png
  src/assets/howto/how-to-select-mode.png
  src/assets/kakaolink_btn_small.png
  src/assets/moview-play.gif
  src/assets/pexels-edmond-dantes.jpg
  src/assets/pexels-tima-miroshnichenko.jpg
  src/assets/pexels-tima-miroshnichenko.webp
  src/components/feedbackModal.jsx
  src/components/header.jsx
  src/index.js
  src/pages/howto.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/login_callback.jsx
  src/pages/main.jsx
  src/store/redirectAtom.js
  src/styles/animation.css
  src/styles/button.hover.css
  src/styles/hamburgerButton.module.css
  src/styles/main.module.css
  src/styles/oauth.module.css
  src/utils/windowHeight.js
Labels: design, refactor, remove

#61 refactor: audioRecorder 리팩토링
  src/utils/audioRecorder.js
Labels: refactor

#63 Remove: Animate Free Effect
  src/pages/main.jsx
  src/styles/main.module.css
Labels: remove

#64 Release v3.2
  .env
  .env.production-dev
  .env.production-main
  public/index.html
  src/App.js
  src/api/api_instance.js
  src/assets/free-icon-close-151882.png
  src/assets/free-icon-hamburger-7710488.png
  src/assets/free-icon-interview-7659465.png
  src/assets/howto/how-to-add-req.png
  src/assets/howto/how-to-chat-mic-edit.png
  src/assets/howto/how-to-chat-mic-off.png
  src/assets/howto/how-to-chat-mic-on.png
  src/assets/howto/how-to-chat-type.png
  src/assets/howto/how-to-input.jpeg
  src/assets/howto/how-to-light.png
  src/assets/howto/how-to-select-mode.png
  src/assets/kakaolink_btn_small.png
  src/assets/moview-play.gif
  src/assets/pexels-edmond-dantes.jpg
  src/assets/pexels-tima-miroshnichenko.jpg
  src/assets/pexels-tima-miroshnichenko.webp
  src/components/feedbackModal.jsx
  src/components/header.jsx
  src/components/loading.jsx
  src/index.js
  src/pages/howto.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/interviewRoom/interviewLightInput.jsx
  src/pages/login_callback.jsx
  src/pages/main.jsx
  src/store/redirectAtom.js
  src/styles/animation.css
  src/styles/button.hover.css
  src/styles/hamburgerButton.module.css
  src/styles/loading.css
  src/styles/main.module.css
  src/styles/oauth.module.css
  src/utils/audioRecorder.js
  src/utils/windowHeight.js
Labels: release
