Repository SWM14-Architect/moview-frontend, pull requests merged in 2023-07, with the labels that each got.

#5 Initial index_RE_1
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/temp_logo.png
  src/components/Logo.jsx
  src/components/footer.jsx
  src/components/header.jsx
  src/index.css
  src/index.js
  src/pages/chat.jsx
  src/pages/end.jsx
  src/pages/index_page.jsx
  src/pages/input.jsx
  src/pages/result.jsx
Labels: rename, feat

#6 Css style add
  src/assets/bot-icon.png
  src/assets/human-icon.png
  src/components/footer.jsx
  src/components/header.jsx
  src/pages/chat.jsx
  src/pages/end.jsx
  src/pages/index_page.jsx
  src/pages/input.jsx
  src/pages/result.jsx
  src/styles/button.css
  src/styles/chat.css
  src/styles/divider.css
  src/styles/end.css
  src/styles/footer.css
  src/styles/form.css
  src/styles/header.css
  src/styles/outer-div.css
  src/styles/result.css
Labels: feat, design, refactor

#7 React-Router를 통한 페이지 이동 구현
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/chat.jsx
  src/pages/end.jsx
  src/pages/index_page.jsx
  src/pages/input.jsx
  src/pages/result.jsx
  src/styles/footer.css
  src/styles/result.css
Labels: feat, chore, refactor

#9 URL Navigator 리팩토링
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/pages/error_page.jsx
  src/pages/index_page.jsx
  src/pages/room.jsx
  src/pages/room/chat.jsx
  src/pages/room/end.jsx
  src/pages/room/input.jsx
  src/pages/room/result.jsx
  src/styles/error.module.css
Labels: fix, refactor

#10 프론트엔드 CI/CD 파이프라인 구축
  .github/workflows/cicd.yml
Labels: feat

#11 Recoil을 통한 전역상태관리 설정
  package-lock.json
  package.json
  src/index.js
  src/pages/index_page.jsx
  src/pages/room.jsx
  src/pages/room/chat.jsx
  src/pages/room/end.jsx
  src/pages/room/input.jsx
  src/pages/room/result.jsx
  src/store/room_atom.js
Labels: feat, chore, refactor

#12 workflow에서 실행시 Deploy 되도록 변경
  .github/workflows/cicd.yml
Labels: chore

#15 Refactor & Feat: 코드 리팩토링 및 ChatBot Page 페이지 추가
  package-lock.json
  package.json
  src/constants/interviewInputConst.js
  src/constants/serviceConst.js
  src/index.js
  src/pages/error_page.jsx
  src/pages/interviewRoom.jsx
  src/pages/interviewRoom/end.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/main.jsx
  src/store/room_atom.js
  src/styles/error.module.css
  src/styles/index.css
  src/styles/interviewChat.module.css
  src/styles/interviewInput.module.css
  src/utils/useInterval.js
  src/utils/useTitle.js
Labels: feat, chore, refactor
