Repository SWM14-Architect/moview-frontend, pull requests merged in 2023-11, with the labels that each got.

#66 design : 메인 페이지에 음성 인식 문구 추가
  src/pages/main.jsx
Labels: design

#67 feat: Google Ads Tag 추가 및 카카오 픽셀 오류 수정
  .env
  public/index.html
  src/index.js
Labels: fix, feat

#68 Release v3.3
  .env
  public/index.html
  src/index.js
  src/pages/main.jsx
Labels: release
