Repository SWM14-Architect/moview-frontend, pull requests merged in 2023-08, with the labels that each got.

#17 feat: API 모듈 구축
  package-lock.json
  package.json
  src/api/interviewee.js
Labels: feat

#18 Refactor & Feat: 코드 리팩토링 및 Feedback 페이지 추가
  package.json
  src/constants/interviewFeedbackConst.jsx
  src/index.js
  src/pages/interviewRoom/end.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/main.jsx
  src/store/room_atom.js
  src/styles/interviewFeedback.module.css
  src/styles/layout.css
  src/styles/radio.input.css
  src/styles/range.input.css
  src/utils/scrollRestoration.jsx
  src/utils/useInterval.js
Labels: fix, feat, design, remove

#19 Refactor & Feat: Feedback 페이지 추가 및 API 요청 및 렌더링 반영
  .env
  .env.production
  package-lock.json
  package.json
  src/api/interviewee.js
  src/components/footer.jsx
  src/components/header.jsx
  src/components/interviewButton.jsx
  src/constants/interviewChatConst.js
  src/constants/interviewFeedbackConst.js
  src/constants/interviewRoomConst.js
  src/index.js
  src/pages/interviewRoom.jsx
  src/pages/interviewRoom/interviewChat.jsx
  src/pages/interviewRoom/interviewFeedback.jsx
  src/pages/interviewRoom/interviewInput.jsx
  src/pages/main.jsx
  src/store/interviewChatAtom.js
  src/store/interviewRoomAtom.js
  src/store/room_atom.js
  src/styles/footer.module.css
  src/styles/index.css
  src/styles/interviewChat.module.css
  src/styles/interviewFeedback.module.css
  src/styles/layout.css
  src/styles/main.module.css
  src/styles/toast.css
  src/utils/interviewSummaryGenerator.js
  src/utils/toastContainer.jsx
Labels: feat, chore, design, refactor
